// reference information is rarely updated, but needs to be handy

char notes[MAX_ENTRIES][MSG_SIZE] = {
" ",
"read book",
" ",
"         [[ today ]] ",
"read book",
"emacs conference",
"renew license",
" ",
"plan marketing",
" ",
"       [[ projects ]] ",
"windows ssd",
" ",
"todo schedule not list",
" ",
"    [[ fun chill ]]  ",
"play FF6",
"write emacs script",
"design 3D",
" ",
"  [[ sow seed ]]",
"craigslist",
"fiver?",
" ",
"  [[ urgent important ]]",
"reversible LH ",
" ",
"  [[ urgent ]]",
"tented signum keeb",
"exercise",
" ",
"  [[ important ]]",
"-- graduate things out --",
"book",
"emacs script",
"redesign keyboard",
"radio license",
"cut ur keeb lol",
" ",
"  [[neither urgent nor impt]]",
"dash magnet",
"mirror to computer",
" ",
"   [[ lowes ]]",
"curtain hanger rod ",
"carpet soap?",
"fire pit 2 tier: $55",
"retaining wall stones 20x",
"lava rock, sand, pea pebbles",
"alum nitrate? ",
"toilet repair kit",
"0.5 in emt conduit 5 ft",
" ",
"    [[ 3d print ]]      ",
"lowpro etoothbrush outlet hanger",
"glasses hanger",
" ",
"            [[ misc ]]",
"hat magnet",
"magnifier onto lamp rm5",
"attach cube shelf to wall",
"steel plate on notebook car dash",
"carpet soap :kroger",
"cough drops kroger:sams",
"soy sauce kroger:sams",
"chili lime cup noodle:kroger",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
" ",
"entry 120",
};

struct todo_entry todos[MAX_TODO_ENTRIES] = {
	{OPEN, 1, "Trouble Tickets"},
	{OPEN, 1, "Voice Mail"},
	{OPEN, 1, "Emails"},
	{OPEN, 1, "Process Orders"},
	{OPEN, 1, "Exercise"},
	{OPEN, 1, "Read 1 chapter bible"},
	{OPEN, 1, "Pray"},
	{OPEN, 1, "Pleasure read 1 sentence"},
	{OPEN, 1, "Be a Husband"},
	{OPEN, 1, "Be a Dad"},
};

// should use lowercase on anything you want to be easily searcheable

const char REFERENCE[][REFERENCE_MSG_SIZE] = {
  "[[ shopping ]]",
  "eggsies x2 :sams:food:aldi:",
  "lemon juice :food:aldi:",
  "chicken ($4.98) :sams:food:",
  "apple juice x2 :sams:",
  "soap :sams:food:",
  "soy sauce :sams:food:",
  "cheese :kroger:food:aldi:",
  "toothpaste :walmart:",
  "jalapenos :sams:food:",
  "bag rice :sams:food:",
  "tuna :sams:food:",
  "veggies :sams:food:kroger:",
  "coffee :kroger:food:aldi:",
  "bisquik :sams:food:",
  "frozen corn cob x2 :sams:food:",
  "ice cream cone :kroger:food:",
  "animal crackers :food:sams:",
  "curry :target:food:",
  "cough drop :walmart:",
  "garlic :sams:food:aldi:",
  " ",
  "[[ laser cutter ]]",
  "[[ pressed board ]]",
  "cut white side 17/100/500 00",
  "pop cut; slower may be necessary for variations in media",
  "engrave white side 80/50",
  "10 speed for a full cut",
  "engrave 55 better",
  " ",
  "[[ .22 acrylic optix ]]",
  " ",
  "engrave 100/100",
  "- need to test",
  "- not very deep, could stand to be slower",
  "cutting 8/100/5000",
  "- complete, fall through cut",
  "- unless a thicker batch?",
  "- using 5 speed is mostly reliable. using 4 now... ",
  "switch ",
  "- alps fit .4 kerf top",
  "- mx .5 kerf",
  "mx speed multipass testing at .5 kerf",
  "- test type the thingy test ",
  " ",
  "[[ . 08 optix acrylic ]]",
  "cut 11/100/5000",
  "clean drop",
  "planck plates 6:59",
  "14?",
  " ",
  "[[ paper ]]",
  "cut 85/10/2500",
  "engrave 90/15",
  " ",
  "[[ books ]]",
  "spring snow - yukio mishima :books:",
  "skin in the game: hidden asymmetries -taleb :books:",
  "antifragile: things that gain from disorder - taleb :books:",
  "woman in the dunes - kobo abe :books:",
  "structure & interpret'n of comp. programs -abelson :books:",
  "count zero - william gibson :books:",
  "a canticle for leibowitz - walter miller :books:",
  "valis - philip k dick :books:",
  "kingdom man :books:",
  "the fourth turning :books:",
  "night falls on the cumberland :books:",
  "buy hatchet (buy) :book:",
  "shogun :books:",
  "red planet :books:",
  "one handed meals :books:",
  "overton window (buy) :books:",
  "the 5000 year leap :books:",
  "the bluegrass conspiracy :books:",
  "a rifleman went to war -mcbride :books:",
  "roughing it :books:",
  "american buffalo :books:",
  " ",
  "[[ misc ]]",
  "[[wifey sandwich ]] :wifey:sandwich:subway:",
  "- footlong ham on wheat.",
  "- pepper jack cheese.",
  "- honey mustard on the bread.",
  "- lots of spinach & cucumbers.",
  "- lettuce, tomatoes salt and pepper.",
  "- lots of oil and vinegar.",
  "- please and thank you!",
  " ",
  "water login/XXXXXXXX :login:",
  "website login/XXXXXXXX :login:",
  "bissell vacuum belt number 7",
  "usps login/XXXXXXXX :login:post:office:",
  "eform atf account XXXXXXXXXXXXXXXXX",
  "eform atf account XXXXXXXXXXXXXX",
  "eform atf account pin XXXX",
  "eform atf user XXXXXXXXXX",
  "church code XXXX",
  "jp2 conversion opj_decompress -i in.jp2 -o out.png",
  "hardware camera mount 1/4x20 nut :hardware:camera:",
  "pinacle :hiking:",
  "red river gorge :hiking:",
  "ravens run :hiking:",
  "kerman :hiking:",
  "big south fork natl park :hiking:",
  " ",
  "[[ g22 ]]",
  "6 @ 50' pumpkin post :g22:",
  "6 @ 33' bisect :g22:",
  "6 @ 21' halfway up front sight :g22:",
  "100 yards? very flat. :g22:",
  "1 @ 50' half way up front sight :g22:",
  "1 @ 21' under base of rear :g22:",
  "4 @ 50' bisect :g22:",
  "4 @ 21' base of front sight :g22:",
  "[[ childrens and names ]] :names:name:kids:",
  "deckart :names:kids:",
  "pico8 lexaloffle username XXXXXXXX",
  "tra704,5,6,8,9 :staples:staplegun:target:",
  "arrow t-50 :staples:staplegun:target:",
  "3010XXXXX :numbers:library:",
  "vin 4S4BRXXXXXXXXXXX :numbers:",
  "XXXX church card ending XXXX",
  "waffle house hashbrowns :waffle:house:hash:hashbrowns:",
  "- smothered covered chunked and capped",
  "lack table :ikea:cincinnati:",
  "Ordning kitchen hobo stove :ikea:cincinnati:",
  "vorda knife :ikea:cincinnati:",
  " ",
  "[[ microcenter ]] :cincinnati:",
  "another pi zero :cincinnati:",
  "pi zero case with camera hole :cincinnati:",
  "3x 32gb sd cards :cincinnati:",
  "new soldering iron tips? :cincinnati:",
  "get a 3d printer :cincinnati:",
  "robot turtles :kids:programming:coding:kid:",
  "lenovo thinkpad t400 :laptop:thinkpad:lenovo:",
  "kindle 8th gen paperwhite pw2 or 3: serial number",
  "lil gun - 300 :powder:gunpowder:",
  "k&n hp-1008 :oil:filter:",
  "hodgdon h4895 m1a :powder:gunpowder:",
  " ",
  "** g22 rear sight :g22:g22:",
  "6 @ 50' pumpkin post",
  "6 @ 33' bisect",
  "6 @ 21' halfway up front sight",
  "1 @ 100 yards? very flat.",
  "1 @ 50' half way up front sight",
  "1 @ 21' under base of rear",
  "4 @ 50' bisect",
  "4 @ 21' base of front sight",
  " ",
  "[[ zelda botw link notes weapons ]] ",
  "these refresh every blood moon",
  "[[ royal claaymore ]] ",
  "- woodland tower (outside korok forest, climp on top of",
  "- skull of tower",
  "[[ gerudo weapons, edge of duality",
  "- gerudo tower, face north, rock on northwest, at base find",
  "- statis-able rock for hidden weapons",
  "[[ great thunderblade",
  "- tabantha tower, glide northwest to other small rock",
  "- protrusion, inside rocks",
  "[[ great flameblade",
  "- go to square labyrinth shrine, go around corner, up",
  "- ledge, follow hall",
  "- central tower hyrule, direct west to ancient treestump",
  "- surrounded by water",
  "- grae torr shrine, west of skull lake, head west eldin",
  "- great skeleton, nortnern edge, skeleton on map",
  "[[ eightfold longblade",
  "- rucco maag shrine, immediately se of elephant, hill",
  "- immediately south has lizafelow with blade",
  "- ta'loh naeg shring (north of kakriko village) go to",
  "- tallest mountain to the w (probably need climbinb set)",
  "[[ royal claymore",
  "- tabinath tower, weapon at base of ne edge of tower,",
  "- grassy area just",
  "- below gannon spikes. many weapons in ground, 3 moblins",
  "[[ royal bow, royal broadsoward, knight's halberd",
  "- shai yota shrine, directly east of elephant, go to talus",
  "- plateau se. hinox has these weapons",
  "[[ knights bow royal bow",
  "- shrine in square labyrinth, climb to top of labyrinth,",
  "- go to nw corner,",
  "- and drop down into the absolute corner",
  "[[ broadsword, shield",
  "- shrine in square labyrinth, go to se outer corner of",
  "- temple stand, step north and drop. climb w then n",
  "[[ knights/royal halberd",
  "- shrine in square labyrinth, ne corner, drop down",
  "[[ various at the colesseum",
  "[[ more powerful royal weapons ]] ",
  "- go to the castle, lol",
  " ",
  "maps ascii map terminal telnet mapscii.me",
  "rain barrels :home:house:",
  "woodburning stove :energy:",
  "smoker grill :home:",
  "tire repair kit :walmart:lowes:",
  "[#a] pvc target stands :lowes:",
  "1/4 nut :lowes:",
  "ladder 8 foot min :home:",
  "sugru :lowes:walmart:",
  "screens :energy:",
  "buy screen channels :lowes:walmart:",
  "storm windows :energy:",
  "tac nails / brads :lowes:walmart:",
  " ",
  "[[ eating out ]] :food:",
  "jets :foodsies:",
  "chipotle :foodsies:",
  "cookout :foodsies:",
  "jimmy johns :foodsies:",
  "subwat :foodsies:",
  "captain ds :foodsies:",
  "indian place :foodsies:",
  "little caesars :foodsies:",
  "burger king :foodsies:",
  " ",
  "[[ cooking ]]",
  "ramen :cooking:",
  "cast iron quesadilla :cooking:",
  "sunday special :cooking:",
  "spaghetti :cooking:",
  "chicken bowls :cooking:",
  "green rice :cooking:",
  "pie yay yuh :cooking:",
  "egg salad sandwich :cooking:",
  "tuna noodles :cooking:",
  "[[ how to beans ]] :recipe:",
  "- rinse and check beans for rocks",
  "- remove any beans floating or malformed",
  "- soak 2 cups (1lb) beans in 10",
  "- cups room temp water, no baking soda",
  "- soak for 24-48 hours",
  "- change water and rinse every 24 hours",
  "- light boil in same qty soak water",
  "- check after 30 mins for tender beans",
  "- remove from heat",
  "- add seasoning to water after tender 30 mins",
  " ",
  "[[ spaghetti generation ]] :recipe:",
  "- larger chunks of beef with salt and basil seasoning",
  "- didnt drain fat (!)",
  "- sliced mushrooms",
  "- fine diced red onion",
  "- add black pepper and a little red pepper",
  "- four fingers of sugar",
  "- whole mushrooms",
  "- red onion :ingredients:",
  " ",
  "[[ ramen ]] :recipe:",
  "start with chicken or 2x bullion cubes",
  "garlic (too much), ginger (not too much)",
  "basil, pepper, red pepper, curry powder",
  "lots of basil, lots of curry powder",
  "add soy sauce (lots) to taste",
  "boil for a bit, taste and season until good",
  "add hard yolk eggs (carefully)",
  "after eggs are hard boiled, scoop into bowl",
  "eggs should be orangeish if you added enough curry",
  "add ramen cakes (top off water if necessary)",
  "add soft boiled eggs now if desired",
  "Mix ramen gently as it softens",
  "turn it over often so it cooks evenly",
  "when noodles are a little hard turn off heat",
  "remove soft boiled egg gently",
  "divide ramen into bowls, pour broth over, serve",
  " ",
  "[[ cast iron lasagna ]] :recipe:",
  "- can diced tomatoes w/ lime and cilantro",
  "- garlic :sams:ingredients:",
  "- pepper :sams:ingredients:",
  "- 2 can tomato sauce :sams:ingredients:",
  "- 1 lb ground beef :sams:kroger:ingredients:",
  "- 16 oz mozzarella :kroger:ingredients:",
  "- oven ready lasagna noodles :kroger:ingredients:",
  "- layer ndl sauc chez ndl sauc ndl chz",
  "- covered in 450 oven for 30, 15 uncovered",
  " ",
  "[[ wifey pantry chili ]] :recipe:",
  "- 2 can corn",
  "- 2 can tri-bean blend",
  "- 16 oz tom sauce",
  "- browned grief",
  "- basil",
  "- oregono",
  "- salt",
  "- thyme",
  " ",
  "[[ sushi rice ]] :recipe:",
  "2 tbsp rice vinegar",
  "2 tbsp sugar",
  "1 teasp salt",
  "mix into 3 cups medium grain rice",
  "can do 2 cups, for stronger flavor",
  " ",
  "[[ bread! ]] :recipe:",
  "basic homemade bread recipe /nmexf7t",
  "5 minute artisan bread /mwcuzmc",
  "cast iron bread! /jlfy4ds",
  " ",
  "[[ prices ]]",
  "- double alum foil 3c/sqft :prices:",
  "- honey 17c/oz :prices:food:",
  "- chunky soup $2 :prices:food:",
  "- ramen 19.08c/package :prices:food:",
  "- soy sauce 8.6c/oz :sams: :prices:food:",
  "- eggs ($1.05)/doz :sams: :prices:food:",
  "- sriracha 28 oz $3.74 :target:prices:food:",
  "- sriracha 17 oz $1.97 :prices:food:",
  "- corn 75.8c/can :prices:food:",
  "- orange juice.. 047/oz :prices:costco:",
  "- green beans 72.7c/can :prices:food:",
  "- penzoil sae 5w30 $3.41/qt :sams:prices:car:",
  "- tuna in water 71.8c/can :prices:food:",
  "- pops cereal 23.9c/oz :prices:food:",
  "- apple jacks cereal 24.5c/oz :prices:food:",
  " ",
  "[[ turkey genders ]]",
  "- wild cherry",
  "- heat sources",
  "- peas and carrots",
  "- jelly beans",
  "- light fog",
  "- pumpkin butter",
  "- bear rug",
  "- leverage better",
  "- break room",
  "- stop mart",
  " ",
  "fitted glasses numbers:",
  "c1 55-18-138",
  " ",
  "[[ ender settings ]]",
  "cura 215 deg pla plus",
  "cura flow rate 94.1 pct, except initial layer flow 100",
  "cura build plate temp 55, initial layer 65",
  "0.01 in (gold) nozzle space on glass bed",
  "first ender 3 motion steps",
  "xsteps/mm 80.44",
  "ysteps/mm 80.00",
  "zsteps/mm 400.00",
  "esteps/mm 100.40",
  " ",
  "XXXXXXXXXX :wifi:",
  "XXXXXXXXXX :wifi:",
  " ",
  "[[ learn reference ]]",
  "wait 60 seconds between pings and alarm when ip addr is up",
  " ping -i 60 -a ip.addr",
  "serve curent direcotry tree on 8000;",
  " python -m simplehttpserver",
  "echo 'ls -l' | at midnight",
  "network monitor ; sudo iftop -i wlp3so",
  "rename filename spaces to underscores;",
  " rename \'y/ /_/\' *",
  "fc to edit new and previous command",
  "export fcedit=vim fc command completion terminal",
  "nmcli wifi command line cli wireless",
  " ",
  "[[ people ]]",
  "terry jury duty thai food",
  "howard buds listed items",
  " ",
  "[[ phone numbers ]]",
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  "name: XXX-XXX-XXXX,"
  " ",
  "[[ fishing trip ]]",
  "fishing tackle",
  "nerd strap",
  "tent and sleeper",
  "headlamp",
  "deep woods off bug spray",
  " ",
  "[[ carbon cure bow string ]]",
  "carbon cure",
  "93 3/16 : string",
  "33 5/8 : cable 1",
  "32 : axel to axel",
  "7 : brace height",
  " ",
  "[[ box stop ]]",
  "box stop 859-271-2393",
  "custom boxes:",
  "6 3/4 x 12 x 1 1/2 box dimensions",
  "$1.50 per box",
  " ",
  "[[ sportsmans warehouse hamburg ]]",
  "2200 War Admiral Way Suite 140, Lexington, KY 40509",
  "859-263-7000",
  "Sun 10A–6PM",
  "Mon 9AM–8PM",
  "Tue 9AM–8PM",
  "Wed 9AM–8PM",
  "Thu 9AM–8PM",
  "Fri 9AM–9PM",
  "Sat 9AM–9PM",
  " ",
  "[[ cabelas ]]",
  "1510 Conservation Way, Lexington, KY 40509",
  "859-286-5300",
  "Sun 10A–7PM",
  "Mon 9AM–8PM",
  "Tue 9AM–8PM",
  "Wed 9AM–8PM",
  "Thu 9AM–8PM",
  "Fri 9AM–8PM",
  "Sat 9AM–8PM",
  " ",
  "[[ fishing ]]",
  "MOVE BAIT S L O W E R",
  "Rod play",
  "Drag",
  "dead stick",
  "pop it",
  "take up slack and tap it",
  "texas rig hook point concealment",
  "wacky rig middle hook worm",
  "work it slowly around cover",
  "bop it jklol",
  "Where are the fish?",
  "Is it hot? Cold? Fish lethargic?",
  "dark colors for dirty water",
  "chatterbait steady reel with speed bursts",
  " ",
  "[[ bow fishing ]]",
  "200lb braided line",
  " ",
  "MIG welder 115v Lincoln ",
  "millermatic 250-2 (no digital readout prefer)",
  " ",
};

// this is the right way to calculate the size of an array of non single byte entries
const long int MAX_REFERENCE_ENTRIES = sizeof(REFERENCE)/ sizeof(REFERENCE[0]);

struct event
// holidays/weekly items which are checked for on day rollover, and a timer is created
// to remind of the event at a useful time.
// file taxes 4/19 @ 09:00
{
	uint8_t month;
	uint8_t date;
	uint8_t weekday;
	uint8_t hour;
	uint8_t minute;
	char message[MSG_SIZE];
};

// if date is 0, check by weekday???
// this works as 1st, 2nd, 3rd wednesday and such. Silliness.
// probably needs a warning processor
// since there is no order, it might be best to sort events here by date

const struct event events[] = {
  // {day, month, weekday, hour, minute, "message"};
  // use 0 day and 0 month to set weekly events for the weekday specified
  //  --------------WEEKLY EVENTS-----------------
  {0, 0, 2, 18, 15, "Prayer tonight"}, // weekly event tuesdays 6:15 pm for prayer
  {0, 0, 4, 18, 10, "Bible Study tonight"}, // weekly event thurs 6:45 pm for bible study
  {0, 0, 0, 9, 45, "Get ready for church"}, // weekly event Sundays 9:45 am to get ready for church
  {0, 0, 3, 17, 0, "Clean piggie cage"}, // weekly event wed 5pm clean piggie cage
  //  ----------------BIRTHDAYS-----------------
  {1, 15, 0, 9, 0, "E birthday"},
  {1, 3, 0, 9, 0, "J birthday"},
  {1, 19, 0, 9, 0, "C birthday"},
  {1, 21, 0, 9, 0, "C birthday"},
  {1, 10, 0, 9, 0, "A birthday"},
  {1, 15, 0, 9, 0, "Anniversary!"},
  {1, 24, 0, 9, 0, "G birthday"},
  {1, 15, 0, 9, 0, "M birthday"},
  {12, 30, 0, 9, 0, "my birthday!"},
  //  --------------YEARLY EVENTS-----------------
  {2, 15, 0, 9, 0, "get candy day"},
  {2, 14, 0, 9, 0, "Valentines day"},
  {3, 14, 0, 9, 0, "daylight savings"},
  {3, 17, 0, 9, 0, "st Pats Day"},
  {4, 1, 0, 9, 0, "April fools"},
  {4, 10, 0, 9, 0, "taxes due soon!"}, // remind on 4/19 @ 10:15am taxes due!
  {4, 15, 0, 9, 0, "taxes due!"}, // remind on 4/19 @ 10:15am taxes due!
  {5, 14, 0, 9, 0, "mothers day"},
  {5, 29, 0, 9, 0, "memorial day"},
  {7, 4, 0, 9, 0, "4th of july"},
  {9, 4, 0, 10, 0, "Labor day"},
  {11, 7, 0, 9, 0, "Daylight Savings time ends"},
  //  ----------------2022 EVENTS-----------------
  // {8, 1, 0, 9, 0, "Mt. rainer garage sale"}, // garage sale
};
// this is the right way to calculate the size of an array of structs
const long int MAX_EVENTS = sizeof(events)/ sizeof(events[0]);

struct event live_events[MAX_LIVE_EVENTS] = {
  // {month, day, weekday, hour, minute, "message"};
  // use 0 day and 0 month to set weekly events for the weekday specified
  {0, 0, 0, INVALID_TIME, 0, "invalid event"},
  {0, 0, 3, 9, 0, "wed at 9"},
  {0, 0, 2, 12, 0, "tues at noon"},
  {0, 0, 1, 9, 0, "monday at 9"},
  {0, 0, 0, 15, 0, "sunday at 3"},
  {0, 0, 0, INVALID_TIME, 0, "invalid event"},
  {0, 0, 3, 9, 0, "wed at 9"},
  {11, 17, 0, 12, 0, "11/17 at noon"},
  {0, 0, 1, 9, 0, "monday at 9"},
  {0, 0, 0, 15, 0, "sunday at 3"},
};
